using System.ComponentModel.DataAnnotations;

#pragma warning disable 1591 //Suppress "Missing XML comment for publicly visible type or member", as most are self-explanatory.

namespace RIVM.ConsExpo.DTO.Models
{
    /// <summary>
    /// A list of the names of all parameters in the system.
    /// </summary>
    /// <remarks>This enum was generated by running in Debug mode and hitting a break-point in which a scenario instance is available.
    /// At that point, the following expressions where evaluated in VS.Net Immediate Window:
    /// ?scenario.DermalExposure
    /// ?scenario.DermalAbsorption
    /// ?scenario.InhalationExposure
    /// ?scenario.InhalationAbsorption
    /// ?scenario.OralExposure
    /// ?scenario.OralAbsorption
    /// These gave all of the properties. Non model parameter fields, like Id and Type fields where then removed.
    /// This can be repeated if model parameters are added.
    /// </remarks>
    public enum ModelParameters
    {
#warning To Do: Maps to which model parameter?

        [Display(Name = "Body weight")] //type: RIVM.ConsExpo.DTO.PhysicalQuantities.BodyWeight
        AssessmentBodyWeight = 100,

        [Display(Name = "Frequency")] //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Frequency
        ScenarioFrequency = 101,

        // {RIVM.ConsExpo.DTO.Models.DermalExposureModel}
        [Display(Name = "Contact time")]
        DermalExposureContactDuration = 1, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ExposureDuration

        [Display(Name = "Contacted surface")]
        DermalExposureContactedSurface = 2, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.RubbingContactArea

        [Display(Name = "Contact rate")]
        DermalExposureContactRate = 3, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ContactRate

        [Display(Name = "Diffusion coefficient")]
        DermalExposureDiffusionCoefficient = 4, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.DiffusionCoefficient

        [Display(Name = "Dislodgeable amount")]
        DermalExposureDislodgeableAmount = 5, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.AreaDensity

        [Display(Name = "Exposed area")]
        DermalExposureExposedArea = 6, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ExposedArea

        [Display(Name = "Exposure duration")]
        DermalExposureExposureDuration = 7, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ExposureDuration

        [Display(Name = "Layer thickness")]
        DermalExposureLayerThickness = 8, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Thickness

        [Display(Name = "Leachable fraction")]
        DermalExposureLeachableFraction = 9, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        [Display(Name = "Product amount")]
        DermalExposureProductAmount = 10, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ProductAmount

        [Display(Name = "Release duration")]
        DermalExposureReleaseDuration = 11, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ReleaseDuration

        [Display(Name = "Skin contact factor")]
        DermalExposureSkinContactFactor = 12, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        [Display(Name = "Substance concentration")]
        DermalExposureSubstanceConcentration = 13, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.SubstanceConcentration

        [Display(Name = "Transfer coefficient")]
        DermalExposureTransferCoefficient = 14, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.TransferCoefficient

        [Display(Name = "Weight fraction substance")]
        DermalExposureWeightFractionSubstance = 15, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        [Display(Name = "Retention factor")]
        DermalExposureRetentionFactor = 16, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.RetentionFactor

        // {RIVM.ConsExpo.DTO.Models.DermalAbsorptionModel}
        [Display(Name = "Absorption fraction")]
        DermalAbsorptionAbsorptionFraction = 20, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        [Display(Name = "Concentration in matrix")]
        DermalAbsorptionConcentrationInMatrix = 21, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.SubstanceConcentration

        [Display(Name = "Exposure duration")]
        DermalAbsorptionExposureDuration = 22, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ExposureDuration

        [Display(Name = "Skin permeability")]
        DermalAbsorptionSkinPermeability = 23, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.SkinPermeability

        // {RIVM.ConsExpo.DTO.Models.InhalationExposureModel}
        [Display(Name = "Airborne fraction")]
        InhalationExposureAirborneFraction = 30, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        [Display(Name = "Application duration")]
        InhalationExposureApplicationDuration = 31, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ApplicationDuration

        [Display(Name = "Application temperature")]
        InhalationExposureApplicationTemperature = 32, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Temperature

#warning To Do: Maps to which model parameter?

        [Display(Name = "Molecular weight")] // To Do
        AssessmentMolecularWeight = 33,

        [Display(Name = "Cloud volume")]
        InhalationExposureCloudVolume = 34, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.CloudVolume

        [Display(Name = "Density non volatile")]
        InhalationExposureDensityNonVolatile = 35, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.DensityNonVolatile

        [Display(Name = "Diffusion coefficient")]
        InhalationExposureDiffusionCoefficientForEmission = 36, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.DiffusionCoefficientForEmission

        [Display(Name = "Emission duration")]
        InhalationExposureEmissionDuration = 37, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.EmissionDuration

        [Display(Name = "Emission duration")]
        InhalationExposureEmissionDurationEvaporation = 38, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.EmissionDurationEvaporation

        [Display(Name = "Exposure duration")]
        InhalationExposureExposureDuration = 39, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ExposureDuration

        [Display(Name = "Exposure duration")]
        InhalationExposureExposureDurationForEmissionModel = 40, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.IntermediateDuration

        [Display(Name = "Inhalation cut-off diameter")]
        InhalationExposureInhalationCutOffDiameter = 41, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Diameter

        [Display(Name = "Inhalation rate")]
        InhalationExposureInhalationRate = 42, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.VolumeRate

        [Display(Name = "Mass generation rate")]
        InhalationExposureMassGenerationRate = 43, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.MassGenerationRate

        [Display(Name = "Mass transfer coefficient")]
        InhalationExposureMassTransferCoefficient = 44, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.MassTransferCoefficient

        [Display(Name = "Maximum diameter")]
        InhalationExposureMaximumDiameter = 45, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.FixedDiameter

        [Display(Name = "Mean diameter")]
        InhalationExposureMeanDiameter = 46, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.FixedDiameter

        [Display(Name = "Median diameter")]
        InhalationExposureMedianDiameter = 47, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.FixedDiameter

        [Display(Name = "Molecular weight matrix")]
        InhalationExposureMolecularWeightMatrix = 48, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.MolecularWeight

        [Display(Name = "Product/air partition coefficient")]
        InhalationExposureProductAirPartitionCoefficient = 49, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.PartitionCoefficient

        [Display(Name = "Product amount")]
        InhalationExposureProductAmount = 50, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ProductAmount

        [Display(Name = "Product density")]
        InhalationExposureProductDensity = 51, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.DensitySolid

        [Display(Name = "Product surface area")]
        InhalationExposureProductSurfaceArea = 52, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ReleaseArea

        [Display(Name = "Product thickness")]
        InhalationExposureProductThickness = 53, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Thickness

        [Display(Name = "Release area")]
        InhalationExposureReleaseArea = 54, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ReleaseArea

        [Display(Name = "Released mass")]
        InhalationExposureReleasedMass = 55, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ProductAmount

        [Display(Name = "Room height")]
        InhalationExposureRoomHeight = 56, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Height

        [Display(Name = "Room volume")]
        InhalationExposureRoomVolume = 57, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.RoomVolume

        [Display(Name = "Spray duration")]
        InhalationExposureSprayDuration = 58, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.SprayDuration

        [Display(Name = "Standard deviation")]
        InhalationExposureStandardDeviation = 59, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.DiameterStandardDeviation

        [Display(Name = "Start exposure")]
        InhalationExposureStartExposure = 60, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.IntermediateDuration

        [Display(Name = "Vapour pressure")]
        InhalationExposureVapourPressure = 62, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Pressure

        [Display(Name = "Ventilation rate")]
        InhalationExposureVentilationRate = 63, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Rate

        [Display(Name = "Weight fraction substance")]
        InhalationExposureWeightFractionSubstance = 64, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        [Display(Name = "Weight fraction substance")]
        InhalationExposureWeightFractionSubstanceForEmission = 65, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        [Display(Name = "Dilution")]
        InhalationExposureDilution = 66, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Dilution

        // {RIVM.ConsExpo.DTO.Models.InhalationAbsorptionModel}
        [Display(Name = "Absorption fraction")]
        InhalationAbsorptionAbsorptionFraction = 70, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        // {RIVM.ConsExpo.DTO.Models.OralExposureModel}
        [Display(Name = "Contact area")]
        OralExposureContactAreaMouthing = 80, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ContactAreaMouthing

        [Display(Name = "Contact area")]
        OralExposureContactAreaPackaging = 81, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ContactAreaPackaging

        [Display(Name = "Exposure duration")]
        OralExposureExposureDuration = 82, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ExposureDuration

        [Display(Name = "Ingested amount")]
        OralExposureIngestedAmountMouthing = 83, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ProductAmount

        [Display(Name = "Ingested amount")]
        OralExposureIngestedAmountPackaging = 84, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ProductAmountPackaging

        [Display(Name = "Ingestion rate")]
        OralExposureIngestionRate = 85, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.IngestionRate

        [Display(Name = "Initial migration rate")]
        OralExposureInitialMigrationRate = 86, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.MigrationRate

        [Display(Name = "Migration rate")]
        OralExposureMigrationRatePackaging = 87, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.MassRatePackaging

        [Display(Name = "Packaged amount")]
        OralExposurePackagedAmount = 88, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ProductAmountPackaging

        [Display(Name = "Product amount")]
        OralExposureProductAmount = 89, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.ProductAmount

        [Display(Name = "Storage time")]
        OralExposureStorageTime = 90, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.StorageTime

        [Display(Name = "Substance concentration")]
        OralExposureSubstanceConcentration = 91, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.SubstanceConcentrationPackaging

        [Display(Name = "Thickness packaging")]
        OralExposureThicknessPackaging = 92, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Thickness

        [Display(Name = "Weight fraction substance")]
        OralExposureWeightFractionSubstance = 93, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        // {RIVM.ConsExpo.DTO.Models.OralAbsorptionModel}
        [Display(Name = "Absorption fraction")]
        OralAbsorptionAbsorptionFraction = 94, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.Fraction

        // {RIVM.ConsExpo.DTO.Models.InhalationExposureModel}
        [Display(Name = "Emission duration")]
        InhalationExposureEmissionDurationReEntry = 95, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.EmissionDurationReEntry

        // {RIVM.ConsExpo.DTO.Models.InhalationExposureModel}
        [Display(Name = "Daily duration")]
        InhalationExposureDailyDuration = 96, //type: RIVM.ConsExpo.DTO.PhysicalQuantities.DailyDuration
    }
}